import { MaterialIcons } from '@expo/vector-icons';
import React, { useEffect, useState } from 'react';
import { ActivityIndicator, ScrollView, StyleSheet, Text, TouchableOpacity, View } from 'react-native';
import { DictOversightSnapshot, getDictOversightSnapshot } from '@/services/dictOversightService';

export default function DataManagementTab() {
  const [data,setData]=useState<DictOversightSnapshot|null>(null); const [loading,setLoading]=useState(true); const [error,setError]=useState('');
  const load=async()=>{setLoading(true);setError('');try{setData(await getDictOversightSnapshot());}catch(e){setError(e instanceof Error?e.message:'Data inventory failed.');}finally{setLoading(false);}}; useEffect(()=>{load();},[]);
  const collections=[['Users',data?.counts.users||0,'Identity directory'],['Reports',data?.counts.reports||0,`${data?.dataQuality.reportsMissingGps||0} missing GPS`],['Schedules',data?.counts.schedules||0,`${data?.dataQuality.completedSchedulesMissingMeasurement||0} completed without measurement`],['Trucks',data?.counts.trucks||0,'Fleet inventory'],['Expense records',data?.counts.expenses||0,`${data?.dataQuality.expensePeriods||0} distinct periods`],['Audit events',data?.counts.auditEvents||0,'Latest server audit window']];
  return <ScrollView style={s.container} contentContainerStyle={s.content}><View style={s.header}><View><Text style={s.eyebrow}>DICT / DATA GOVERNANCE</Text><Text style={s.title}>Data Management</Text><Text style={s.sub}>Live collection inventory, completeness checks, and operational data readiness.</Text></View><TouchableOpacity style={s.refresh} onPress={load}><MaterialIcons name="refresh" size={18} color="#374151" /><Text style={s.refreshText}>Refresh inventory</Text></TouchableOpacity></View>{loading&&!data?<ActivityIndicator size="large" color="#4F46E5"/>:null}{!!error&&<Text style={s.error}>{error}</Text>}<View style={s.table}><View style={s.tableHead}><Text style={[s.th,{flex:1.2}]}>DATASET</Text><Text style={[s.th,{width:100}]}>RECORDS</Text><Text style={[s.th,{flex:2}]}>QUALITY SIGNAL</Text><Text style={[s.th,{width:100}]}>STATUS</Text></View>{collections.map(([name,count,signal])=><View key={String(name)} style={s.row}><Text style={[s.name,{flex:1.2}]}>{name}</Text><Text style={[s.count,{width:100}]}>{count}</Text><Text style={[s.signal,{flex:2}]}>{signal}</Text><View style={[s.badge,{width:100}]}><View style={s.dot}/><Text style={s.badgeText}>CONNECTED</Text></View></View>)}</View><View style={s.quality}><Text style={s.qualityTitle}>Readiness Gates</Text><View style={s.gates}>{[['GPS completeness',(data?.dataQuality.reportsMissingGps||0)===0,`${data?.dataQuality.reportsMissingGps||0} missing`],['Measured pickups',(data?.dataQuality.completedSchedulesMissingMeasurement||0)===0,`${data?.dataQuality.completedSchedulesMissingMeasurement||0} incomplete`],['Budget backtest',(data?.dataQuality.expensePeriods||0)>=3,`${data?.dataQuality.expensePeriods||0}/3 periods`]].map(([label,ok,detail])=><View key={String(label)} style={s.gate}><MaterialIcons name={ok?'check-circle':'pending'} size={23} color={ok?'#16A34A':'#D97706'}/><Text style={s.gateLabel}>{label}</Text><Text style={s.gateDetail}>{detail}</Text></View>)}</View></View></ScrollView>;
}
const s=StyleSheet.create({container:{flex:1,backgroundColor:'#F8FAFC'},content:{padding:28},header:{flexDirection:'row',justifyContent:'space-between',gap:16,marginBottom:22},eyebrow:{fontSize:10,fontWeight:'900',color:'#4F46E5',letterSpacing:1.1},title:{fontSize:26,fontWeight:'900',color:'#0F172A',marginTop:5},sub:{fontSize:12,color:'#64748B',marginTop:5},refresh:{flexDirection:'row',alignItems:'center',gap:7,borderWidth:1,borderColor:'#CBD5E1',backgroundColor:'#FFF',borderRadius:9,paddingHorizontal:13,paddingVertical:9},refreshText:{fontSize:11,fontWeight:'800',color:'#374151'},error:{color:'#B91C1C',backgroundColor:'#FEF2F2',padding:12,borderRadius:9,marginBottom:14},table:{backgroundColor:'#FFF',borderWidth:1,borderColor:'#E2E8F0',borderRadius:14,overflow:'hidden'},tableHead:{flexDirection:'row',padding:13,backgroundColor:'#F1F5F9'},th:{fontSize:9,fontWeight:'900',color:'#64748B',letterSpacing:.7},row:{flexDirection:'row',alignItems:'center',padding:15,borderTopWidth:1,borderTopColor:'#F1F5F9'},name:{fontSize:12,fontWeight:'900',color:'#0F172A'},count:{fontSize:15,fontWeight:'900',color:'#4F46E5'},signal:{fontSize:11,color:'#64748B'},badge:{flexDirection:'row',alignItems:'center',gap:6},dot:{width:7,height:7,borderRadius:4,backgroundColor:'#10B981'},badgeText:{fontSize:8,fontWeight:'900',color:'#166534'},quality:{backgroundColor:'#FFF',borderWidth:1,borderColor:'#E2E8F0',borderRadius:14,padding:17,marginTop:16},qualityTitle:{fontSize:14,fontWeight:'900',color:'#0F172A'},gates:{flexDirection:'row',flexWrap:'wrap',gap:12,marginTop:12},gate:{flex:1,minWidth:180,backgroundColor:'#F8FAFC',borderRadius:11,padding:14},gateLabel:{fontSize:11,fontWeight:'900',color:'#334155',marginTop:8},gateDetail:{fontSize:9,color:'#64748B',marginTop:3}});
